### ISSUE TITLE
The unrealistic Gyr in SFH file

### ISSUE THREAD

**Issue by dartoon** [mtakahiro/gsf#44]
After running gsf fit, the age marks in SFH is incorrect for this running.
[202301152_freeParam_withEmissionLine.zip](https://github.com/mtakahiro/gsf/files/10443322/202301152_freeParam_withEmissionLine.zip)

**Comment by mtakahiro** [comment]
This was caused by a duplicated input in the AGE column in sample.input:

AGE			0.3,**0.4**,0.5,**0.4**,0.7 #I only select one value

After 2598c4d, error message will show up in such case.

**Comment by dartoon** [comment]
Right!!! Thanks!
